server:
  port: 8092
spring:
  application:
    name : candidate-profile-screening
  ai:
    openai:
      api-key: ahjj
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      generate_statistics: false
      show-sql: true
  datasource:
    #change as per your system
    url: jdbc:mysql://localhost:3306/candidate
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: bharatkorlahalli12@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
perplexity:
  api:
    key:
  base-url : https://api.perplexity.ai/chat/completions
jwt:
  secret: myssdesfefcfsfecrhjfgwjfirehifjolfkpfwdwsfghwewqfwqghpldgdsczvbnesecrfsfwsfwswetkey
  expiration: 3600000